# -*- coding: utf-8 -*-
"""
Created on Mon Mar 23 19:27:31 2026

@author: Kamila Dudzińska
"""

# pipeline

# import modułów
import pandas as pd
from data_loader import load_data
import data_loader
from config import url_conn1, DB_HOST, DB_PASSWORD, create 
from sqlalchemy import create_engine
from sql_query import sql_filmy
from df_analysis import(
    revenue_by_location,
    active_customers_by_location,
    customer_segments,
    add_segments,
    revenue_by_segment,
    segment_by_activity,
    customer_number,
    segments_share_per,
    top_country_by_segment,
    language2
    )


# %%
def main():
    df = load_data()
    
    #dodanie segmentów
    df = add_segments(df)
    
    
    # analizy
    
    #przychód w zależnoci od lokacji
    revenue_location = revenue_by_location(df)
    print(df.shape)
    print(df['amount'].dtype)
    print(df['country'].drop_duplicates().shape)
    print('The biggest revenue is generated by: ')
    print(revenue_location.head(5))
    print()
    
    #liczba aktywnych klientów wg kraju
    active_cust_loc = active_customers_by_location(df)
    print(f'Największa liczba aktywnych klientów jest w następujących krajach:')
    print(active_cust_loc.head(5))
    print()

    # przychody wg segmentu klientów
    segment_revenue = revenue_by_segment(df)
    print('Przychody wg segmentów klientów: ')
    print(segment_revenue.head(5))
    print()
    

    # segmentacja iloci klientów względem kraju
    segment_country = top_country_by_segment(df)
    print('Segmentacja klientów wg krajów: ')
    print(segment_country)
    print()
    
    
    #liczba klientów, w poszczególnych segmentach
    num_customers = customer_number(df)
    print(num_customers)
    print()
    
    #liczba filmów oferowanych wg języka
    silnik = create_engine(url_conn1, future=True)
    print('Języki oraz iloć filmów dostępnych w nich: ')
    print(language2(silnik))
    print()
    
    # output do csv/xlsx
    print(f' zapisanie wyników do pliku exel.')
    
    with pd.ExcelWriter('Pełna Analiza.xlsx', engine = 'openpyxl') as writer:
        revenue_location.to_excel(writer, sheet_name="Revenue by location", index = False)
        active_cust_loc.to_excel(writer, sheet_name="Active customer_by_location", index = False)
        segment_revenue.to_excel(writer, sheet_name="Revenue_by_segment", index = False)
        segment_country.to_excel(writer, sheet_name="Segment_by_country", index = False)
        num_customers.to_excel(writer, sheet_name="Customer_number_by_segment", index = False)
    
if __name__ == "__main__":
    main()
